/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as HousingRequestRouteImport } from './routes/housing-request'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestViewingIdRouteImport } from './routes/request-viewing.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingRequestRoute = HousingRequestRouteImport.update({
  id: '/housing-request',
  path: '/housing-request',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestViewingIdRoute = RequestViewingIdRouteImport.update({
  id: '/request-viewing/$id',
  path: '/request-viewing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/guide': typeof GuideRoute
  '/housing-request': typeof HousingRequestRoute
  '/landlord': typeof LandlordRoute
  '/my-requests': typeof MyRequestsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/listing/$id': typeof ListingIdRoute
  '/request-viewing/$id': typeof RequestViewingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/guide': typeof GuideRoute
  '/housing-request': typeof HousingRequestRoute
  '/landlord': typeof LandlordRoute
  '/my-requests': typeof MyRequestsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/listing/$id': typeof ListingIdRoute
  '/request-viewing/$id': typeof RequestViewingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/faq': typeof FaqRoute
  '/favorites': typeof FavoritesRoute
  '/guide': typeof GuideRoute
  '/housing-request': typeof HousingRequestRoute
  '/landlord': typeof LandlordRoute
  '/my-requests': typeof MyRequestsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/listing/$id': typeof ListingIdRoute
  '/request-viewing/$id': typeof RequestViewingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compare'
    | '/faq'
    | '/favorites'
    | '/guide'
    | '/housing-request'
    | '/landlord'
    | '/my-requests'
    | '/profile'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/listing/$id'
    | '/request-viewing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compare'
    | '/faq'
    | '/favorites'
    | '/guide'
    | '/housing-request'
    | '/landlord'
    | '/my-requests'
    | '/profile'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/listing/$id'
    | '/request-viewing/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compare'
    | '/faq'
    | '/favorites'
    | '/guide'
    | '/housing-request'
    | '/landlord'
    | '/my-requests'
    | '/profile'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/listing/$id'
    | '/request-viewing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  FaqRoute: typeof FaqRoute
  FavoritesRoute: typeof FavoritesRoute
  GuideRoute: typeof GuideRoute
  HousingRequestRoute: typeof HousingRequestRoute
  LandlordRoute: typeof LandlordRoute
  MyRequestsRoute: typeof MyRequestsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ListingIdRoute: typeof ListingIdRoute
  RequestViewingIdRoute: typeof RequestViewingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing-request': {
      id: '/housing-request'
      path: '/housing-request'
      fullPath: '/housing-request'
      preLoaderRoute: typeof HousingRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-viewing/$id': {
      id: '/request-viewing/$id'
      path: '/request-viewing/$id'
      fullPath: '/request-viewing/$id'
      preLoaderRoute: typeof RequestViewingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  FaqRoute: FaqRoute,
  FavoritesRoute: FavoritesRoute,
  GuideRoute: GuideRoute,
  HousingRequestRoute: HousingRequestRoute,
  LandlordRoute: LandlordRoute,
  MyRequestsRoute: MyRequestsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ListingIdRoute: ListingIdRoute,
  RequestViewingIdRoute: RequestViewingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
